#ifndef AVOIDPEOPLE_MODULE_GLOBAL_H
#define AVOIDPEOPLE_MODULE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AVOIDPEOPLE_MODULE_LIBRARY)
#  define AVOIDPEOPLE_MODULESHARED_EXPORT Q_DECL_EXPORT
#else
#  define AVOIDPEOPLE_MODULESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AVOIDPEOPLE_MODULE_GLOBAL_H
